### ISSUE TITLE
 Error on create my Zimbra Docker‏

### ISSUE THREAD

**Issue by valdirrosendo** [Zimbra-Community/zimbra-docker#10]
Hello Jorge,

I´m trying to create my Zimbra Docket, i follow exactly the process of https://github.com/Zimbra-Community/zimbra-docker,
but i found two problems:

1.  this url is not found,  wget https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/docker/start.sh
2. after call the command "sudo IMAGE=zimbra_docker make" i´m receiving the error: "make: *** No targets specified and no makefile found.  Stop".

**Comment by barrydegraaff** [comment]
try it again, we fixed the url

**Comment by barrydegraaff** [comment]
start.sh seems to be missing

**Comment by emanuelUngureanu** [comment]
Until its fixed, the script can be found in google cache: https://webcache.googleusercontent.com/search?q=cache:3SprLeoe2KYJ:https://raw.githubusercontent.com/jorgedlcruz/Zimbra/master/docker/start.sh+&cd=7&hl=en&ct=clnk&gl=ro

A simple modified version is ( added line 67 to make it work): 
[start.sh.txt](https://github.com/Zimbra-Community/zimbra-docker/files/186984/start.sh.txt)

**Comment by barrydegraaff** [comment]
emanuelUngureanu: thanks, I added the start,sh back to this repository, can you confirm all works now?

valdirrosendo: can you confirm all works now?
Thanks Barry

**Comment by barrydegraaff** [comment]
See also https://github.com/Zimbra-Community/zimbra-docker/commit/41e862800096d60577ef3126bb26fa42f9ca6035

I opened a discussion on the removal of start.sh

**Comment by washingtoneg** [comment]
Hey @valdirrosendo. That's an issue with the instructions. You have to be to the docker directory (`cd docker`) in order to run the `make` command.

Can you give that a try and let me know if that works?

**Comment by barrydegraaff** [comment]
washingtoneg: thanks for the info!
