### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by emanuelUngureanu** [Zimbra-Community/zimbra-docker#12]
Wget is missing and start.sh fails at "Installing mailboxd certificates". 
The scripts from opt/zimbra-install/ seem to be fine,also if i use ZimbraEasyInstall in the docker container instead of start.sh it works.

**Comment by quantumtechnology** [comment]
I can confirm the problem.

**Comment by jorgedlcruz** [comment]
Hello, I don't know what's going on, I can't make it work either, I can't even build the image properly:
Step 6 : COPY opt /opt/
lstat opt: no such file or directory

@washingtoneg Do you mind to explain us all the steps to make it work after your commits? thank you

Best regards

**Comment by quantumtechnology** [comment]
I still struggle even with ZimbraEasyInstall.
But how I got the image was by doing a "git clone" and then
a "sudo make". I added wget and removed the autostart of start.sh.

**Comment by jorgedlcruz** [comment]
I am trying now another steps, the ones @washingtoneg added, which are, clone or wget the master.zip, unzip it, and move into the docker folder, do sudo make, that will create a image, then launch the next command: docker run -h zimbra86-docker.zimbra.io --dns 127.0.0.1 --dns 8.8.8.8 -i -t -e PASSWORD=Zimbra2015 zimbra_docker
It will create the container, I'm still downloading the Zimbra image

**Comment by jorgedlcruz** [comment]
It's fixed now, you need to clone the repo again, or download the master.zip and unziped it:
Then move under docker folder and run: sudo make
Then launch the command: docker run -p 25:25 -p 80:80 -p 465:465 -p 587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 443:443 -p 8080:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 -h zimbra86-docker.zimbra.io --dns 127.0.0.1 --dns 8.8.8.8 -i -t -e PASSWORD=Zimbra2015 zimbra_docker

**Comment by quantumtechnology** [comment]
Thanks a lot, I have to try it right now.
One thing I realized as in the outer host I do not have dns I need to avoid --dns 127.0.0.1. This is not an issue is it?

**Comment by jorgedlcruz** [comment]
Hi @quantumtechnology try it and let us know

**Comment by quantumtechnology** [comment]
Thanks now it runs through perfectly. Thanks for the help.
I am just wondering how to keep it running.
It basically ends and the next time I run the same command it will do the same installation.

**Comment by jorgedlcruz** [comment]
Hi @quantumtechnology you can just run:
```
docker ps -a 
docker start YOURCONTAINERID
docker exec -it YOURCONTAINERID bash
su - zimbra
zmcontrol restart
```
You can now exit from the shell, but the container will keep up and running

**Comment by quantumtechnology** [comment]
Thanks for the help I forgot about the -a option... :)

**Comment by barrydegraaff** [comment]
reopen for adding to readme

**Comment by emanuelUngureanu** [comment]
Awesome, thanks @jorgedlcruz !
