### ISSUE TITLE
ssh keys are not installed due to apt-get install ssh missing

### ISSUE THREAD

**Issue by quantumtechnology** [Zimbra-Community/zimbra-docker#13]
There seems to be the ssh keys missing, such that web app is not working properly.
to fix:
apt-get install ssh
su - zimbra
zmsshkeygen
zmupdateauthkeys

**Comment by quantumtechnology** [comment]
Then I still get an error with sending mail with local mail:
method:	[unknown]
msg:	SMTP server reported: MESSAGE_NOT_DELIVERED
code:	mail.SEND_FAILURE
detail:	soap:Sender
trace:	qtp509886383-124:https://172.17.0.2:8443/service/soap/SendMsgRequest:1459133093538:e1c385f2a6305a72
request:	

Body: {
  SendMsgRequest: {
    _jsns: "urn:zimbraMail",
    m: {
      e: [
        // [0]:
        {
          a: "admin@quantumtechnology.info",
          p: "admin",
          t: "t"
         },
        // [1]:
        {
          a: "admin@quantumtechnology.info",
          t: "f"
         }
       ],
      idnt: "cf0d0ccf-c49d-4a16-ba30-97bb84840d2a",
      mp: [
        // [0]:
        {
          ct: "multipart/alternative",
          mp: [
            // [0]:
            {
              content: {
                _content: "test 
"
               },
              ct: "text/plain"
             },
            // [1]:
            {
              content: {
                _content: "&lt;html&gt;&lt;body&gt;&lt;div style=&quot;font-family: arial, helvetica, sans-serif; font-size: 12pt; color: #000000&quot;&gt;&lt;div&gt;test&lt;br data-mce-bogus=&quot;1&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;"
               },
              ct: "text/html"
             }
           ]
         }
       ],
      su: {
        _content: "test"
       }
     },
    suid: 1459133159923
   }
 },
Header: {
  context: {
    _jsns: "urn:zimbra",
    account: {
      _content: "admin@quantumtechnology.info",
      by: "name"
     },
    authToken: "(removed)",
    csrfToken: "0_629c46b820bfce74d134a6c54a38bb4ed86eb1e2",
    notify: {
      seq: 1
     },
    session: {
      _content: 11,
      id: 11
     },
    userAgent: {
      name: "ZimbraWebClient - FF45 (Win)",
      version: "8.6.0_GA_1153"
     }
   }
 }

**Comment by quantumtechnology** [comment]
Hints:
________________
 I call docker (current master release of Dockerfile and start.sh) with 
sudo docker run -p 25:25 -p 81:80 -p 465:465 -p 587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 444:443 -p 8081:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 -h www.quantumtechnology.info --dns 134.93.8.159 --dns 134.93.8.13 -i -t -e PASSWORD=XXXX zimbra_docker 
____________
I need to use 81 8081 and 444 because ports are taken on outer host.
The host outer host name is quantumtechnology.info
with alias www.quantumtechnology.info

I put A and MX DNS record on the outer server by ISP.
______________________
--dns 127.0.0.1 usage leads to docker not resolving hostnames
_____
I also installed letsencrypt certificates but issue remains.

**Comment by quantumtechnology** [comment]
I did now the following nonautomated steps to get a zimbra docker up and running. This might be helpful for you to correct your script:

sudo docker run -h mail.quantumtechnology.local -it -p 26:25 -p 81:80 -p 465:465 -p 587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 443:443 -p 8080:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 ubuntu:14.04
#inside docker
apt-get update
apt-get install libgmp10 libperl5.18 unzip pax sysstat sqlite3 dnsmasq wget libaio1 vim dnsutils ssh

vim /etc/dnsmasq.conf
#we add external dns server inside docker:
user=root
server=192.168.145.2
domain=quantumtechnology.local
mx-host=quantumtechnology.local, mail.quantumtechnology.local, 5
mx-host=mail.quantumtechnology.local, mail.quantumtechnology.local, 5
listen-address=127.0.0.1
####################################

vim /etc/resolv.conf
#:
# Generated by NetworkManager
search localdomain
nameserver 127.0.0.1
#####################################
service dnsmasq restart
wget https://files.zimbra.com/downloads/8.6.0_GA/zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116.tgz
tar -xvf zcs-8.6.0_GA_1153.UBUNTU14_64.20141215151116.tgz
cd zcs*
./install.sh
#do N at zimbra-dsncache
#set admin pw
#use keys: 6 4 PASSWORD r a y

You also need to edit /etc/ssh/sshd_config, and comment out the following line:
PermitRootLogin without-password

Just below it, add the following line:

PermitRootLogin yes
Then restart SSH:
sudo service ssh restart

su – zimbra
zmsshkeygen
zmupdateauthkeys
#If you have a multi-server environment, run this command on the other servers:
zmupdateauthkeys
zmcontrol restart

**Comment by barrydegraaff** [comment]
Thanks for your feedback, for now you can try out one of the below solutions:

For testing purposes we recommend the Zextras docker, multiple versions: https://hub.docker.com/r/zextras/zimbra8/

For production purpose (work in progress), Zimbra docker from Zimbra upstream: https://github.com/Zimbra/zm-docker
