### ISSUE TITLE
Docker container stops

### ISSUE THREAD

**Issue by cloud-rocket** [Zimbra-Community/zimbra-docker#16]
I am trying to use docker scripts, without too much luck....

Zimbra installation (start.sh) finished with no problem:

The last lines I am receiving are:
```
Starting servers...done.
Installing common zimlets...
    com_zimbra_*...done.
Finished installing common zimlets.
Restarting mailboxd...done.
Creating galsync account for default domain...done.
Setting up zimbra crontab...done.


Moving /tmp/zmsetupXXX.log to /opt/zimbra/log

Moving /tmpzmsetupXXX.log to /opt/zimbra/log
```

Afterward I run

```
docker start zimbra
docker exec -it zimbra bash
su - zimbra
zmcontrol restart
```

"zmcontrol status" shows that all services are running, but few seconds afterwards the container stops by itself with no error messages. 

I am able to load login screen before it stops....

**Comment by cloud-rocket** [comment]
Ok, I figured out the problem - I added "-d" as an argument to start.sh withing Dockerfile....

**Comment by jorgedlcruz** [comment]
Would you mind to edit the file here, or tell us where exactly?

Best regards

**Comment by cloud-rocket** [comment]
zimbra-docker/docker/opt/start.sh have an option to enable endless loop with "-d" argument (lines 149-151)
It could be enabled within Dockerfile by changing:
`CMD ["/bin/bash", "/opt/start.sh"]` to `CMD ["/bin/bash", "/opt/start.sh", "-d"]`
Otherwise the script is finished and container is closed

Anyway if the container is restarted, all Zimbra services still need to be started manually by
```
docker exec -it zimbra bash
su - zimbra
zmcontrol start
```

**Comment by cloud-rocket** [comment]
Also you need to add openssh-client within Dockerfile apt-get install section, because it is not installed with base Ubuntu 14.04 image and it is needed to generate auth keys

**Comment by jorgedlcruz** [comment]
Done both changes, thank you !
