### ISSUE TITLE
Zimbra services appear as not running within Admin console

### ISSUE THREAD

**Issue by cloud-rocket** [Zimbra-Community/zimbra-docker#17]
All services are marked with "X" inside Server Status page.

When I log into docker bash, change the user to "zimbra" and run "zmcontrol status" - all services appear to be running...

Thanks

**Comment by jorgedlcruz** [comment]
Hi, this is an expected behavior, you can restart your container and next time will appear in green.

**Comment by cloud-rocket** [comment]
It doesn't help (and any way you need to start the services manually as I mentioned in [here](https://github.com/Zimbra-Community/zimbra-docker/issues/16)

The server is working (i.e. Emails are sent) and I can manage users. But within monitoring section all services appear down.

**Comment by mvhconsult** [comment]
Any update on this, as it appears to be a continuous issue.
Hints on causes: 
- https://www.jorgedelacruz.es/2015/11/11/zimbra-zmhactl-missing-or-not-executable/
- https://forums.zimbra.org/viewtopic.php?t=59432

**Comment by kerozen54** [comment]
Same here, i have done what is explain and keep the services appearing not runing in the web admin console.

**Comment by UralZima** [comment]
Hi. That's because zimbra-logger is not running. It can't run without syslog-ng package.
I posted some instructions for new ZCS, that fixing this issue. https://github.com/Zimbra-Community/zimbra-docker/issues/27

**Comment by longmikel** [comment]
Hi, i've running zimbra web console, but it always show "Some services are not running"  but in zmcontrol status all services running fine.
how can i fix this ?﻿

**Comment by UralZima** [comment]
apt-get install syslog-ng
sed -i 's/internal();//g' /etc/syslog-ng/syslog-ng.conf
service syslog-ng restart

**Comment by longmikel** [comment]
Hi, I deployed on CentOS 7 environment so I tried with rsyslog but did not find any results.

Looking forward to getting a new idea on this bug problem.

**Comment by thanhdt1404** [comment]
This site can help you guys fix this shit on CentOS 7. https://www.huuphan.com/2016/11/zimbra-some-services-are-not-running.html

**Comment by branzo** [comment]
@longmikel ..that happens because CentOS 7 is a systemd-based distro and the distro's setup needs systemd running for rsyslog to successfully start (the same is true for Ubuntu16), you could try applying this inside the container:

 sed -i"" 's/$ModLoad imjournal/#$ModLoad imjournal/g' /etc/rsyslog.conf
 sed -i"" 's/$IMJournalStateFile imjournal.state/#$IMJournalStateFile imjournal.state/g' /etc/rsyslog.conf 
 sed -i"" 's/$OmitLocalLogging on/$OmitLocalLogging off/g' /etc/rsyslog.conf
 rm /etc/rsyslog.d/listen.conf

then you could restart rsyslog...

**Comment by barrydegraaff** [comment]
Thanks for your feedback, for now you can try out one of the below solutions:

For testing purposes we recommend the Zextras docker, multiple versions: https://hub.docker.com/r/zextras/zimbra8/

For production purpose (work in progress), Zimbra docker from Zimbra upstream: https://github.com/Zimbra/zm-docker
