### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by lliccien** [Zimbra-Community/zimbra-docker#20]
after creating the image with the command -t build zimbra-docker docker.
NEXT command is run

root@mail:/home/administrador/zimbra-docker/docker# docker run -p 25:25 -p 80:80 -p 465:465 -p 587:587 -p 110:110 -p 143:143 -p 993:993 -p 995:995 -p 443:443 -p 8080:8080 -p 8443:8443 -p 7071:7071 -p 9071:9071 -h mail.cufm.tec.ve --dns 127.0.0.1 --dns 8.8.8.8 -i -t -e PASSWORD=pass zimbra-docker

after running is the cotenedor stops in this message

ERROR

Configuration failed

Please address the error and re-run /opt/zimbra/libexec/zmsetup.pl to
complete the configuration.

Errors have been logged to /tmp/zmsetup05242016-024238.log

the same is true if I think the image to make

I use ubuntu 14.04

**Comment by aydent** [comment]
UP, 
Same issue, and my /tmp was empty (on my container and hosts). 
I continue to invastigate.

**Comment by thomasfriedl** [comment]
Same issue for me.

**Comment by 1of16** [comment]
hi,

try to edit docker/opt/start.sh line 4 (hostname -a) to (hostname -s)
sed -i "s/hostname -a/hostname -s/" docker/opt/start.sh

worked for me...

**Comment by barrydegraaff** [comment]
Thanks for your feedback, for now you can try out one of the below solutions:

For testing purposes we recommend the Zextras docker, multiple versions: https://hub.docker.com/r/zextras/zimbra8/

For production purpose (work in progress), Zimbra docker from Zimbra upstream: https://github.com/Zimbra/zm-docker
