### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by funnybones** [Zimbra-Community/zimbra-docker#21]
Hi! 

I have a concern regarding the data storage. In this configuration, will the data be saved on disk or inside the container? If so, how can I back-up zimbra data so I can assure failure recovery?

Thank you,
Alex.

**Comment by jorgedlcruz** [comment]
Hi funnybones, 
This script saves the data inside the docker, you can protect your data with tools like Zimbra Backup Plus, which protect much better and in real time your Zimbra Platform, is a commercial solution:
https://www.zimbra.com/zimbra-suite-plus/zimbra-backup-plus/

Best regards
