### ISSUE TITLE
Install zimbra on a docker build rather than the docker run

### ISSUE THREAD

**Issue by SaadE92** [Zimbra-Community/zimbra-docker#23]
Hi,
  After building the image and running a container everything is working fine, however is there any way to make all the installation and configuration stuff on the 'docker build' rather than the 'docker run':
   Maybe by setting statically the HOSTNAME, DOMAIN and CONTAINERIP on the start.sh.
 in that way it's possible to run a new container and be able to start zimbra service instantly.
I have tried this but i have an error that says to fix the /etc/hosts file.
Thank you for your help

**Comment by jorgedlcruz** [comment]
Hi Saad92, I couldn't make it work the way you are asking, which it will be really cool and automated, let me know if you find how to do it.

Best regards
