### ISSUE TITLE
Docker port maping 

### ISSUE THREAD

**Issue by bouab002** [Zimbra-Community/zimbra-docker#25]
I have problem with port mapping , docker is not listening on my public ip address can someone help please.

# netstat -tulapn
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      448/sshd        
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      422/rpcbind     
tcp        0      0 0.0.0.0:54576           0.0.0.0:*               LISTEN      431/rpc.statd             
tcp6       0      0 :::22                   :::*                    LISTEN      448/sshd        
tcp6       0      0 :::25                   :::*                    LISTEN      4818/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      4786/docker-proxy
tcp6       0      0 :::8443                 :::*                    LISTEN      4730/docker-proxy
tcp6       0      0 :::7071                 :::*                    LISTEN      4746/docker-proxy
tcp6       0      0 :::993                  :::*                    LISTEN      4762/docker-proxy
tcp6       0      0 :::995                  :::*                    LISTEN      4754/docker-proxy
tcp6       0      0 :::45865                :::*                    LISTEN      431/rpc.statd   
tcp6       0      0 :::587                  :::*                    LISTEN      4770/docker-proxy
tcp6       0      0 :::110                  :::*                    LISTEN      4802/docker-proxy
tcp6       0      0 :::143                  :::*                    LISTEN      4794/docker-proxy
tcp6       0      0 :::9071                 :::*                    LISTEN      4722/docker-proxy
tcp6       0      0 :::111                  :::*                    LISTEN      422/rpcbind     
tcp6       0      0 :::80                   :::*                    LISTEN      4810/docker-proxy
tcp6       0      0 :::8080                 :::*                    LISTEN      4738/docker-proxy
tcp6       0      0 :::465                  :::*                    LISTEN      4778/docker-proxy
udp        0      0 0.0.0.0:39801           0.0.0.0:*                           401/dhclient    
udp        0      0 0.0.0.0:1021            0.0.0.0:*                           422/rpcbind     
udp        0      0 0.0.0.0:68              0.0.0.0:*                           401/dhclient    
udp        0      0 127.0.0.1:608           0.0.0.0:*                           431/rpc.statd   
udp        0      0 0.0.0.0:111             0.0.0.0:*                           422/rpcbind     
udp        0      0 0.0.0.0:37617           0.0.0.0:*                           431/rpc.statd   
udp6       0      0 :::1021                 :::*                                422/rpcbind     
udp6       0      0 :::111                  :::*                                422/rpcbind     
udp6       0      0 :::29848                :::*                                401/dhclient    
udp6       0      0 :::42352                :::*                                431/rpc.statd

**Comment by branzo** [comment]
Hi @bouab002 

have you ran the command inside or outside the container?

**Comment by barrydegraaff** [comment]
Thanks for your feedback, for now you can try out one of the below solutions:

For testing purposes we recommend the Zextras docker, multiple versions: https://hub.docker.com/r/zextras/zimbra8/

For production purpose (work in progress), Zimbra docker from Zimbra upstream: https://github.com/Zimbra/zm-docker
