### ISSUE TITLE
commit the installation ?

### ISSUE THREAD

**Issue by kerozen54** [Zimbra-Community/zimbra-docker#26]
Hi all.
Just after starting my first zimbra-docker, i realize that if i stop it and restart it, it download and configure zimbra once again.
How to prevent this and make a full usable zimbra docker ?

regards

**Comment by UralZima** [comment]
Hi man. I tried to use this zimbra-docker scripts, but they totally fail and are not usable.
Try my method: https://github.com/Zimbra-Community/zimbra-docker/issues/27
I installed a newest version 8.7.2 from scratch, minimum components, working well and commit available.

**Comment by barrydegraaff** [comment]
Thanks for your feedback, for now you can try out one of the below solutions:

For testing purposes we recommend the Zextras docker, multiple versions: https://hub.docker.com/r/zextras/zimbra8/

For production purpose (work in progress), Zimbra docker from Zimbra upstream: https://github.com/Zimbra/zm-docker
