### ISSUE TITLE
Non ascii username and passwords in zimbra

### ISSUE THREAD

**Issue by Nitin29** [Zimbra-Community/zimbra-docker#4]
Hi 

We are trying to create non-ascii users in ZIMBRA for internationalization of our mail services.

But getting error of invalid request.

Looking for support on the above 

Nitin

**Comment by jorgedlcruz** [comment]
Hi Nitin29, 
You should go to bugzilla.zimbra.com and fill a Bug there for it. Search for it first, I remember to saw it.

Best regards

**Comment by Nitin29** [comment]
Hi jorgedlcruz,

I raised the issue as suggested by you but as per my understanding its not a bug its a new feature.

Internationalization of mailbox names, usernames and passwords.

Best Regards,
Nitin

**Comment by jorgedlcruz** [comment]
You can open a Bug with a RFE in the Zimbra Bugzilla, I can't do nothing else here, as I'm not Zimbra Developer working for Zimbra writing code.

Bugzilla it's the best way, Zimbra developers will start working on it if we have enough votes.

Best regards

**Comment by Nitin29** [comment]
ok , thnks for your suggestion

Best Regards

**Comment by Nitin29** [comment]
How may votes required ?

**Comment by Nitin29** [comment]
How Many votes can help us ?

**Comment by jorgedlcruz** [comment]
Hi Nitin29,
I'm not sure, did you manage to search by the actual opened Bugs about it?

Best regards

**Comment by Nitin29** [comment]
Hi Jorge

I searched the whole web but till date no success.
It will be great if u can put some light on

Regards,
nitin

**Comment by barrydegraaff** [comment]
I am closing this issue, as it is not a zimbra-docker issue, please report upstream https://bugzilla.zimbra.com/ if the problem persists.

Thanks
