### ISSUE TITLE
Container re-installs after every launch - persistent storage

### ISSUE THREAD

**Issue by agent2** [Zimbra-Community/zimbra-docker#6]
After building the image and deploying the container, eventually I can see that Zimbra finishes installing... and then the container shuts off! If I restart the container, the start.sh runs and installation occurs all over again. I assume there is something that I am doing wrong here since I'm new to Docker?

**Comment by Schinti95** [comment]
You could try changing the Dockerfile and use this instead of the normal CMD command on the last line.

     CMD ["/bin/bash", "/tmp/zcs/start.sh", "-d"]

**Comment by vavai** [comment]
Hi, 

I'm currently encounter similar problems, installing on Docker on top of Ubuntu 14.04 64 bit. Changing the Dockerfile as suggested has no effect, container are exit after all process was successfully installed.

Is there anything else to check according to this problem?

**Comment by fweng322** [comment]
I think that you may need to rebuild the docker image after changing the Dockerfile.

**Comment by barrydegraaff** [comment]
If someone can figure out how to have persistent storage with zimbra-docker, please share your effort so we can integrate it here.

**Comment by barrydegraaff** [comment]
The data should be persistent, so maybe we need some more documentation / wiki on how to use the Zimbra Docker

**Comment by barrydegraaff** [comment]
2:51:35 PM - Jorge-zimb: Here
2:51:36 PM - Jorge-zimb: https://youtu.be/nWvmqmWmjKk?t=403
2:51:51 PM - Jorge-zimb: They are talking about that stuff
2:52:05 PM - Jorge-zimb: once deployed, the container closes, and you need to start it manually :)
2:52:08 PM - Jorge-zimb: That must be fixed

**Comment by fweng322** [comment]
You can add "-d" as the parameter of start. sh in Dockerfile, then rebuild
the image.  Run the newly built image and when everything is done it will
be in an endless sleep loop.  While Zimbra is running, commit the docker
instance in another terminal.

Franklin

-- 
Sent from my phone
2016/2/26 下午9:52於 "Barry de Graaff" <notifications@github.com>寫道：

**Comment by barrydegraaff** [comment]
@fweng322 thanks for the answer, I will close this issue for for now. If someone wants to, please add a wiki page to this repo with more how-to.

Regards, Barry
